[project]
name = "pandas-cleaning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Re7ab", email = "re7ab.su95@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
]


[dependency-groups]
dev = [
    "black>=26.5.1",
    "ipykernel>=7.3.0",
    "mypy>=2.3.1",
    "ruff>=0.16.8",
]
